# Generated by Django 3.0.3 on 2020-02-20 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='description',
            field=models.TextField(blank=True, default='Some_desc', max_length=100, verbose_name='Description to category'),
        ),
        migrations.AddField(
            model_name='cat',
            name='paginated',
            field=models.PositiveIntegerField(default=0, verbose_name='Kolvo posts on page'),
        ),
        migrations.AddField(
            model_name='cat',
            name='published',
            field=models.BooleanField(default=0, verbose_name='Otobrazhat?'),
        ),
        migrations.AddField(
            model_name='cat',
            name='sort',
            field=models.PositiveIntegerField(default=0, verbose_name='Sort'),
        ),
        migrations.AddField(
            model_name='cat',
            name='template',
            field=models.CharField(default='blog/post_list', max_length=100, verbose_name='Shablon'),
        ),
        migrations.AddField(
            model_name='post',
            name='edit_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of edit'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/', verbose_name='Main image'),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=True, verbose_name='To Publish?'),
        ),
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of publish'),
        ),
        migrations.AddField(
            model_name='post',
            name='sort',
            field=models.PositiveIntegerField(default=0, verbose_name='To sort'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Registered only'),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Short_desc'),
        ),
        migrations.AddField(
            model_name='post',
            name='template',
            field=models.CharField(default='blog/post_list.html', max_length=100, verbose_name='Shablon'),
        ),
        migrations.AddField(
            model_name='post',
            name='viewed',
            field=models.PositiveIntegerField(default=0, verbose_name='Was viewed?'),
        ),
        migrations.AddField(
            model_name='tag',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Otobrazhat?'),
        ),
    ]
